name: Check code quality

on:
  workflow_call: ~
  pull_request: ~
  push:
    branches: ['master', 'release']

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install poetry
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx install poetry

    - name: Validate the structure of the pyproject.toml
      run: poetry check

    - name: Verify that poetry.lock is consistent with pyproject.toml
      run: poetry lock --check

    - name: Install dependencies
      run: poetry install

    - name: Lint code by ruff
      run: poetry run ruff .

    - name: Check types by pyright
      run: poetry run pyright

    - name: Run tests
      run: poetry run pytest

